application: we-so-smart
version: 1
runtime: python
api_version: 1

handlers:  
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /scripts
  static_dir: scripts
  
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /(signup|login)
  script: welcome.py
  secure: optional
  
- url: /(verify|logout).*
  script: welcome.py

- url: /act.*
  script: welcome.py

- url: /settings
  script: welcome.py
  secure: optional
  
- url: /.*
  script: welcome.py
